// tools/progressClaims/deriveReferenceWeights.ts
// Regenerates referenceStageWeights.data.ts from the RAB workbooks in
// assets/BOQ. Run from the repo root:
//   npx tsx tools/progressClaims/deriveReferenceWeights.ts
import * as fs from 'fs';
import * as path from 'path';
import { referenceProfile } from './referenceStageWeights';
import { loadReferenceWorkbooks, referenceWorkbooksAvailable } from './loadReferenceWorkbooks';

const root = process.cwd();
const boqDir = path.join(root, 'assets', 'BOQ');
if (!referenceWorkbooksAvailable(boqDir)) {
  console.error('Reference RAB workbooks not found under assets/BOQ; run from the repo root.');
  process.exit(1);
}

const profile = referenceProfile(loadReferenceWorkbooks(boqDir));
const out = process.argv[2] ?? path.join(root, 'tools', 'progressClaims', 'referenceStageWeights.data.ts');
fs.writeFileSync(
  out,
  [
    '// GENERATED by tools/progressClaims/deriveReferenceWeights.ts from the RAB workbooks',
    '// listed in referenceStageWeights.ts REFERENCE_WORKBOOKS. Do not edit by hand; re-run:',
    '//   npx tsx tools/progressClaims/deriveReferenceWeights.ts',
    "import type { ReferenceProfile } from './stageWeights';",
    '',
    `export const REFERENCE_PROFILE: ReferenceProfile = ${JSON.stringify(profile, null, 2)};`,
    '',
  ].join('\n'),
);
console.log(`wrote ${path.relative(root, out)}`);
for (const [cls, entry] of Object.entries(profile)) {
  if (!entry) continue;
  const w = entry.weights;
  console.log(`${cls.padEnd(26)} bek ${(w.BEKISTING * 100).toFixed(1)}%  pem ${(w.PEMBESIAN * 100).toFixed(1)}%  cor ${(w.PENGECORAN * 100).toFixed(1)}%  (${entry.workbooks} workbooks, ${entry.rows} rows, ${entry.volume_m3} m3)`);
}
