// GENERATED by tools/progressClaims/deriveReferenceWeights.ts from the RAB workbooks
// listed in referenceStageWeights.ts REFERENCE_WORKBOOKS. Do not edit by hand; re-run:
//   npx tsx tools/progressClaims/deriveReferenceWeights.ts
import type { ReferenceProfile } from './stageWeights';

export const REFERENCE_PROFILE: ReferenceProfile = {
  "PILECAP_SLOOF_PLAT_DASAR": {
    "weights": {
      "BEKISTING": 0.131,
      "PEMBESIAN": 0.476,
      "PENGECORAN": 0.393
    },
    "workbooks": 5,
    "rows": 125,
    "volume_m3": 608
  },
  "KOLOM": {
    "weights": {
      "BEKISTING": 0.326,
      "PEMBESIAN": 0.486,
      "PENGECORAN": 0.188
    },
    "workbooks": 5,
    "rows": 208,
    "volume_m3": 313
  },
  "BALOK_PLAT": {
    "weights": {
      "BEKISTING": 0.368,
      "PEMBESIAN": 0.38,
      "PENGECORAN": 0.252
    },
    "workbooks": 5,
    "rows": 441,
    "volume_m3": 1143
  },
  "DINDING": {
    "weights": {
      "BEKISTING": 0.312,
      "PEMBESIAN": 0.356,
      "PENGECORAN": 0.332
    },
    "workbooks": 5,
    "rows": 54,
    "volume_m3": 464
  }
};
